### ISSUE TITLE
Adding stream chat dependency

### ISSUE THREAD

**Issue by Blutree-Technets** [Blutree-Technets/RealHeroS-master#1]
We need to add stream chat dependency to our pubspec file without any clashes with existing dependencies.
package name:
stream_chat_flutter: ^1.5.4

website-https://pub.dev/packages/stream_chat_flutter

we want to implement a chat page in our application where there is a single channel and all users can chat with each other, there should be an option to share photos, videos, and voice texts to let the user request help.

Stream chat API key- 8ypq8rq9t8py
Stream chat API secret-utsac792ptgcbtnm2cd994db4m4xg7qkwcjzq5hft6k9scq2pg6xhugzczgn8u7p

**Comment by GJJ2019** [comment]
closing this issue as I added stream_chat_flutter dep in @varunshilesh
